<?php

$imageTitles = [
    'IMG_1.jpg' => 'Great Pyramid of Giza',
    'IMG_2.jpg' => 'Temple of Artemis',
    'IMG_3.jpg' => 'Statue of Zeus at Olympia',
    'IMG_4.jpg' => 'Hanging Gardens of Babylon',
    'IMG_5.jpg' => 'Lighthouse of Alexandria',
    'IMG_6.jpg' => 'Mausoleum at Halicarnassus',
    'IMG_7.jpg' => 'Colossus of Rhodes',
];

$imageDescriptions =[
    'IMG_1.jpg' => "The Great Pyramid of Giza is one of the Seven Wonders of the Ancient World and is the largest pyramid ever built in ancient times.\nLocated near Cairo, Egypt, it is considered one of the most impressive architectural feats in history.\nThe Great Pyramid, built around the 26th century BCE, originally stood at a height of approximately 146.6 meters (about 481 feet), though its current height is around 138.8 meters (about 455 feet) due to the loss of its upper casing stones.\nThe pyramid is constructed from limestone blocks, which were transported from various quarries in the region, with each block weighing between 2.5 to 15 tons.\nThe exterior was originally covered with white Tura limestone, giving it a bright and shining appearance.",
    'IMG_2.jpg' => "The Temple of Artemis at Ephesus was one of the Seven Wonders of the Ancient World and is regarded as one of the most magnificent structures built in ancient history.\nThe temple was dedicated to the Greek goddess Artemis, the goddess of hunting, nature, fertility, and childbirth.\nArtemis was one of the most important deities in Greek mythology, and the temple at Ephesus served as a central place of worship dedicated to her.\nThe first temple was likely constructed in the 8th century BCE.\nHowever, the temple that achieved fame as one of the Seven Wonders was rebuilt in the 6th century BCE under the patronage of Croesus, the wealthy king of Lydia.\nThe construction was overseen by the architects Chersiphron and his son Metagenes, and the temple was built on a vast scale, making it one of the largest religious structures of its time.",
    'IMG_3.jpg' => "The Statue of Zeus at Olympia was one of the Seven Wonders of the Ancient World and is regarded as one of the most impressive works of art from ancient Greece.\nThe statue was created in the 5th century BCE by the sculptor Phidias and was located in the Temple of Zeus in Olympia, where the ancient Olympic Games were held.\nThe Statue of Zeus was primarily made of ivory, with the use of gold and precious materials to create a magnificent appearance.\nStanding at approximately 12 meters tall, the statue depicted Zeus seated on his throne.\nIn his right hand, he held a figure of Nike (the goddess of victory), while in his left hand, he held a scepter topped with an eagle.\nThe overall appearance of the statue was stunning, showcasing intricate details and unique artistic craftsmanship.",
    'IMG_4.jpg' => "The Hanging Gardens of Babylon are one of the Seven Wonders of the Ancient World and are considered one of the most magnificent and luxurious structures ever built.\nAccording to historical accounts and legends, the gardens were constructed in the city of Babylon (present-day Iraq) in the 6th century BCE, likely by King Nebuchadnezzar II.\nHe built them for his wife, Queen Amytis, who was of Persian origin and missed the green mountainous landscapes of her homeland.\nThe gardens were created to provide her with a sense of home.\nHistorical descriptions suggest that the Hanging Gardens consisted of a series of terraced plants and trees built upon high structures, giving the appearance that they were 'hanging' in the air.\nThe design included trees and columns that supported the weight of the vegetation, with water cascading from irrigation channels over the lush plants.\nThe overall appearance of the gardens was akin to a moving paradise, filled with colors, scents, and breathtaking views.",
    'IMG_5.jpg' => "The Lighthouse of Alexandria, also known as the Pharos of Alexandria, was one of the Seven Wonders of the Ancient World and is considered one of the most impressive architectural feats of its time.\nThe lighthouse was built on the island of Pharos, located near the city of Alexandria in Egypt, in the 3rd century BCE.\nThe Lighthouse of Alexandria was remarkably tall, estimated to stand between 100 to 130 meters (about 330 to 430 feet). It consisted of three main tiers: a square base, a circular midsection, and a towering top section.\nThe lighthouse was adorned with sculptures and featured a fire at its peak to guide sailors safely into the harbor.\nAt night, the bright light from the fire helped mariners navigate their way.",
    'IMG_6.jpg' => "The Mausoleum at Halicarnassus was one of the Seven Wonders of the Ancient World and is regarded as one of the most magnificent architectural creations of its time.\nLocated in Halicarnassus (modern-day Bodrum, Turkey), the mausoleum was built in the 4th century BCE to serve as a tomb for Mausolus, the ruler of Caria, and his wife, Artemisia.\nThe mausoleum was designed to be an extravagant structure, standing approximately 45 meters tall.\nIt featured a multi-tiered base, with a central chamber known as the 'Mausoleum'.\nThe building was adorned with numerous sculptures, reliefs, and columns, all showcasing exquisite artistic craftsmanship.\nThe roof was crowned with a chariot sculpture pulled by horses, symbolizing grandeur and power.",
    'IMG_7.jpg' => "The Colossus of Rhodes was one of the Seven Wonders of the Ancient World and is considered one of the most magnificent artistic creations of the time.\nThis giant statue was erected in the city of Rhodes, Greece, and was dedicated in the 3rd century BCE following the city’s victory over King Demetrius.\nThe Colossus was a massive statue of the sun god Helios, standing approximately 33 meters tall (about 108 feet), making it one of the tallest statues of the ancient world.\nIt was positioned at the entrance of the harbor of Rhodes and was constructed of bronze plates over an iron framework.\nThe statue was renowned for its impressive size and detailed design, which included intricate features such as ornaments, flowing hair, and expressive facial features.",
];


